name: CI (Build • Test • Coverage • Java 25)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: 'maven'

      - name: Show Java & Maven
        run: |
          java -version
          mvn -v

      - name: Build & run tests (H2 test profile)
        run: mvn -B clean verify -Dspring.profiles.active=test

      # Upload test reports so you can read them in the Actions UI
      - name: Upload surefire test reports (unit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload failsafe reports (integration, if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failsafe-reports
          path: target/failsafe-reports/
          if-no-files-found: ignore

      - name: Upload JaCoCo coverage (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage
          path: target/site/jacoco/
          if-no-files-found: ignore

      - name: Package JAR (skip tests for faster packaging)
        run: mvn -q -DskipTests package

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
