name: Release (Build JAR • Publish)

on:
  push:
    tags:
      - 'v*.*.*'   # e.g., v1.0.0

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: 'maven'

      - name: Build (run all tests)
        run: mvn -B clean verify

      - name: Package JAR (skip tests)
        run: mvn -q -DskipTests package

      - name: Determine tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and upload JAR
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.TAG }}
          name: "SmartWarehouse WMS ${{ steps.vars.outputs.TAG }}"
          draft: false
          prerelease: false
          files: |
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
